Pair Programming - 17 - nov - 2025

#### **Creación y Indexación:**

1. Crea un array 1D con 50 valores aleatorio del 10 al 99. Accede a los elementos en las posiciones múltiplos de 5.

In [1]:
import numpy as np

In [17]:
array_randint_uni = np.random.randint(10,100, (50))

In [18]:
print(array_randint_uni)

[74 79 51 39 98 11 78 50 51 27 34 85 18 13 90 68 16 30 95 96 86 92 63 18
 47 72 37 13 90 94 17 55 38 18 57 88 37 53 57 19 16 56 71 10 53 86 70 72
 83 76]


In [20]:
array_randint_uni[0::5]

array([74, 11, 34, 68, 86, 72, 17, 88, 16, 86], dtype=int32)

2. Crea un array 1D con 30 valores aleatorios del 1 al 20 (ambos incluidos). Utiliza indexación para obtener los elementos en las posiciones impares.

In [21]:
array_randint_uni_2 = np.random.randint(1,21, (30))

In [22]:
print(array_randint_uni_2)

[10 20 18  8 18 20 15  9  2  7 11  5 10 12 15 12 11  5  6 16 19 17 12  1
  3 10  9  9  3 19]


In [ ]:
array_randint_uni_2[1::2]   # posiciones impar

array([20,  8, 20,  9,  7,  5, 12, 12,  5, 16, 17,  1, 10,  9, 19],
      dtype=int32)

3. Crea un array 2D de forma (4, 6) con números aleatorios decimales (no deben estar comprendidos solo entre 0 y 1). Accede a la última fila de la matriz. Los decimales deben estar redondeados a 2 decimales.

In [28]:
a = 3

In [29]:
b = 0.5

In [30]:
a + b

3.5

In [33]:
array_randdecimal = np.random.rand(4,6)
print(array_randdecimal)

[[0.04263436 0.9242569  0.2850003  0.34866285 0.98042602 0.79797151]
 [0.0916589  0.88106521 0.58423483 0.09719929 0.19846039 0.30786314]
 [0.13679419 0.00230473 0.23864899 0.14420815 0.31129108 0.84958939]
 [0.16839725 0.61165126 0.37980564 0.48134146 0.14350043 0.49200747]]


In [ ]:
array_randdecimal_2 = np.random.randint(1,5,(4,6))
print(array_randdecimal_2)

[[2 2 2 2 4 1]
 [3 3 2 2 4 1]
 [3 4 4 2 4 1]
 [4 3 1 2 2 4]]


In [34]:
array_final = array_randdecimal + array_randdecimal_2
print(array_final)


[[2.04263436 2.9242569  2.2850003  2.34866285 4.98042602 1.79797151]
 [3.0916589  3.88106521 2.58423483 2.09719929 4.19846039 1.30786314]
 [3.13679419 4.00230473 4.23864899 2.14420815 4.31129108 1.84958939]
 [4.16839725 3.61165126 1.37980564 2.48134146 2.14350043 4.49200747]]


In [36]:
np.round(array_final, 2)    # , 2 es redondear a 2 decimales

array([[2.04, 2.92, 2.29, 2.35, 4.98, 1.8 ],
       [3.09, 3.88, 2.58, 2.1 , 4.2 , 1.31],
       [3.14, 4.  , 4.24, 2.14, 4.31, 1.85],
       [4.17, 3.61, 1.38, 2.48, 2.14, 4.49]])

3. Crea un array 2D de forma (4, 6) con números aleatorios decimales (no deben estar comprendidos solo entre 0 y 1). Accede a la última fila de la matriz. Los decimales deben estar redondeados a 2 decimales.

In [38]:
array_final_2 = np.round(array_final, 2) 
print(array_final_2)

[[2.04 2.92 2.29 2.35 4.98 1.8 ]
 [3.09 3.88 2.58 2.1  4.2  1.31]
 [3.14 4.   4.24 2.14 4.31 1.85]
 [4.17 3.61 1.38 2.48 2.14 4.49]]


In [ ]:
array_final_2[][::]  # A finalizar!!!

In [ ]:
# array_randdecimal = np.random.uniform((4,6))  no lo sabemos usar..

In [ ]:
array_randdecimal = np.random.rand((4,6))

In [ ]:
# array_redondeado = np.round(array_aleatorio, 2)

In [27]:
array_randdecimal

array([[0.72526699, 0.63725691, 0.23438072, 0.12412265, 0.31371834,
        0.39668618],
       [0.21810631, 0.66877032, 0.20315654, 0.08956201, 0.79340495,
        0.02524279],
       [0.94813036, 0.80223121, 0.93485431, 0.20727128, 0.81694025,
        0.33026138],
       [0.70241342, 0.88253912, 0.50872459, 0.77901638, 0.41631867,
        0.44384465]])

#### **Funciones Aritméticas y Estadísticas:**

1. Crea un array de tres 3D con elementos entre el 0 y 1 de forma (2, 3, 5) cuyos valores solo tengan 1 decimal.